debug: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

app:
  redis:
    url: noucake.ddns.net
    port: 6379


spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://noucake.ddns.net:3306/aztube
    username: root
    password: rootpw
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    enabled-by-default: false # disable all actuator endpoints by default
    jmx:
      exposure:
        include: '*'
    web:
      base-path: /actuator
      exposure:
        include: health

  endpoint: # enable only those endpoints we want
    health:
      enabled: true
      group: # special health endpoints for kubernetes probes
        readyness:
          include: readyness
        liveness:
          include: liveness