debug: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

server:
  error:
    include-message: always

app:
  cas:
    url: https://login.united-internet.org/ims-sso
    apiurl: https://api.azplace.azubi.server.lan/auth/verify
    redirecturl: https://azplace.azubi.server.lan
  defaultKeyValidTime: 120

  redis:
    url: noucake.ddns.net
    port: 6379
    password:


spring:
  elasticsearch:
    uris: http://elastic.azplace.azubi.server.lan
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://noucake.ddns.net:3306/aztube
    username: root
    password: rootpw
    driver-class-name: com.mysql.cj.jdbc.Driver

  session:
    store-type: jdbc
    jdbc:
      table-name: SPRING_SESSION
      cleanup-cron: 0 */15 * * * *
      initialize-schema: embedded
      schema: classpath:/session_schema.sql

management:
  endpoints:
    enabled-by-default: false # disable all actuator endpoints by default
    jmx:
      exposure:
        include: '*'
    web:
      base-path: /actuator
      exposure:
        include: health

  endpoint: # enable only those endpoints we want
    health:
      enabled: true
      group: # special health endpoints for kubernetes probes
        readyness:
          include: readyness
        liveness:
          include: liveness