debug: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

server:
  error:
    include-message: always

app:
  cas:
    url: https://login.united-internet.org/ims-sso
    apiurl: https://api.azplace.azubi.server.lan/auth/verify
    redirecturl: https://azplace.azubi.server.lan
  defaultKeyValidTime: 120

  redis:
    url: noucake.ddns.net
    port: 6379
    password:

spring:
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  redis:
    port: 6379
    host: noucake.ddns.net
  elasticsearch:
    uris: http://elastic.azplace.azubi.server.lan

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://noucake.ddns.net:3306/aztube
    username: root
    password: rootpw
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        include: '*'
    web:
      base-path: /actuator
      exposure:
        include: health

  endpoint:
    health:
      enabled: true
      group: # special health endpoints for kubernetes probes
        readyness:
          include: readyness
        liveness:
          include: liveness