name: Build Test

on: [ pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: maven/3.8-amazoncorretto-17
    steps:
      - uses: actions/checkout@v3
      - name: Build with Maven
        run: mvn clean install